export const btnList = [
    /*PS3                  PS4 / PS5            Wiimote             Wiimote + Classic        Wiimote + Classic Pro  Wiimote + Nunchuck   WiiU / Switch Pro    Switch NES           Switch SNES          Switch MD / Genesis  Switch N64           Switch Joycon        Xbox One S / X|S     Steam                8bitdo SN30/SF30     8bitdo M30           Google Stadia        Exlene GameCube      OG XBOX */
    ['Left stick left',   'Left stick left',   '',               '[C] Left stick left',   '[C] Left stick left',    '[N] Stick left',   'Left stick left',   '',                  '',                  '',                  'Stick left',        'Stick left (H)',    'Left stick left',   'Left pad left',     'Left stick left',   '',                  'Left stick left',   'Left stick left',   'Left stick left',   ],
    ['Left stick right',  'Left stick right',  '',               '[C] Left stick right',  '[C] Left stick right',   '[N] Stick right',  'Left stick right',  '',                  '',                  '',                  'Stick right',       'Stick right (H)',   'Left stick right',  'Left pad right',    'Left stick right',  '',                  'Left stick right',  'Left stick right',  'Left stick right',  ],
    ['Left stick down',   'Left stick down',   '',               '[C] Left stick down',   '[C] Left stick down',    '[N] Stick down',   'Left stick down',   '',                  '',                  '',                  'Stick down',        'Stick down (H)',    'Left stick down',   'Left pad down',     'Left stick down',   '',                  'Left stick down',   'Left stick down',   'Left stick down',   ],
    ['Left stick up',     'Left stick up',     '',               '[C] Left stick up',     '[C] Left stick up',      '[N] Stick up',     'Left stick up',     '',                  '',                  '',                  'Stick up',          'Stick up (H)',      'Left stick up',     'Left pad up',       'Left stick up',     '',                  'Left stick up',     'Left stick up',     'Left stick up',     ],
    ['Right stick left',  'Right stick left',  '',               '[C] Right stick left',  '[C] Right stick left',   '',                 'Right stick left',  '',                  '',                  '',                  'C-Left',            '',                  'Right stick left',  'Right pad left',    'Right stick left',  '',                  'Right stick left',  'Right stick left',  'Right stick left',  ],
    ['Right stick right', 'Right stick right', '',               '[C] Right stick right', '[C] Right stick right',  '',                 'Right stick right', '',                  '',                  '',                  'C-Right',           '',                  'Right stick right', 'Right pad right',   'Right stick right', '',                  'Right stick right', 'Right stick right', 'Right stick right', ],
    ['Right stick down',  'Right stick down',  '',               '[C] Right stick down',  '[C] Right stick down',   '',                 'Right stick down',  '',                  '',                  '',                  'C-Down',            '',                  'Right stick down',  'Right pad down',    'Right stick down',  '',                  'Right stick down',  'Right stick down',  'Right stick down',  ],
    ['Right stick up',    'Right stick up',    '',               '[C] Right stick up',    '[C] Right stick up',     '',                 'Right stick up',    '',                  '',                  '',                  'C-Up',              '',                  'Right stick up',    'Right pad up',      'Right stick up',    '',                  'Right stick up',    'Right stick up',    'Right stick up',    ],
    ['D-pad left',        'D-pad left',        'D-pad left (H)', '[C] D-pad left',        '[C] D-pad left',       '[W] D-pad left (V)', 'D-pad left',        'D-pad left',        'D-pad left',        'D-pad left',        'D-pad left',        '',                  'D-pad left',        'Stick left',        'D-pad left',        'D-pad left',        'D-pad left',        'D-pad left',        'D-pad left',        ],
    ['D-pad right',       'D-pad right',       'D-pad right (H)','[C] D-pad right',       '[C] D-pad right',      '[W] D-pad right (V)','D-pad right',       'D-pad right',       'D-pad right',       'D-pad right',       'D-pad right',       '',                  'D-pad right',       'Stick right',       'D-pad right',       'D-pad right',       'D-pad right',       'D-pad right',       'D-pad right',       ],
    ['D-pad down',        'D-pad down',        'D-pad down (H)', '[C] D-pad down',        '[C] D-pad down',       '[W] D-pad down (V)', 'D-pad down',        'D-pad down',        'D-pad down',        'D-pad down',        'D-pad down',        '',                  'D-pad down',        'Stick down',        'D-pad down',        'D-pad down',        'D-pad down',        'D-pad down',        'D-pad down',        ],
    ['D-pad up',          'D-pad up',          'D-pad up (H)',   '[C] D-pad up',          '[C] D-pad up',         '[W] D-pad up (V)',   'D-pad up',          'D-pad up',          'D-pad up',          'D-pad up',          'D-pad up',          '',                  'D-pad up',          'Stick up',          'D-pad up',          'D-pad up',          'D-pad up',          'D-pad up',          'D-pad up',          ],
    ['',                  '',                  '',               '[W] D-pad left (H)',    '[W] D-pad left (H)',    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  'L pad click',       '',                  '',                  'Capture',           '',                  '',                  ],
    ['',                  '',                  '',               '[W] D-pad right (H)',   '[W] D-pad right (H)',   '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  'R pad click',       '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',               '[W] D-pad down (H)',    '[W] D-pad down (H)',    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',               '[W] D-pad up (H)',      '[W] D-pad up (H)',      '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['Square',            'Square',            '1',                '[C] Y',                 '[C] Y',               '[W] 1',             'Y',                 'B',                 'Y',                 'A',                 'B',                 'B | D-pad up',      'X',                 'X',                 'Y',                 'A',                 'X',                 'Y',                 'X',                 ],
    ['Circle',            'Circle',            'B',                '[C] A',                 '[C] A',               '[W] 2',             'A',                 '',                  'A',                 'C',                 '',                  'X | D-pad down',    'B',                 'B',                 'A',                 'C',                 'B',                 'A',                 'B',                 ],
    ['X',                 'X',                 '2',                '[C] B',                 '[C] B',               '[W] A',             'B',                 'A',                 'B',                 'B',                 'A',                 'A | D-pad left',    'A',                 'A',                 'B',                 'B',                 'A',                 'B',                 'A',                 ],
    ['Triangle',          'Triangle',          'A',                '[C] X',                 '[C] X',               '',                  'X',                 '',                  'X',                 'Y',                 '',                  'Y | D-pad right',   'Y',                 'Y',                 'X',                 'Y',                 'Y',                 'X',                 'Y',                 ],
    ['Start',             'OPTIONS',           '+',                '[C] +',                 '[C] +',               '',                  '+',                 'Start',             'Start',             'Start',             'Start',             '+ | Capture',       'Menu',              'Start',             'Start',             'Start',             'Menu',              'Start',             'Start',             ],
    ['Select',            'SHARE',             '-',                '[C] -',                 '[C] -',               '',                  '-',                 'Select',            'Select',            'Mode',              '',                  '- | Home',          'View',              'Back',              'Select',            'Minus',             'Options',           '',                  'Back',              ],
    ['PS',                'PS',                'Home',             '[C] Home',              '[C] Home',            '',                  'Home',              '',                  '',                  'Home',              'Home',              '',                  'Xbox',              'Steam',             'Home',              'Home',              'Stadia',            '',                  '',                  ],
    ['',                  'TouchPad',          '',                 '[W] B',                 '[W] B',               '',                  'Capture',           '',                  '',                  'Capture',           'Capture',           '',                  'Share',             'Stick click',       '',                  '',                  'Assitant',          '',                  '',                  ],
    ['L2',                'L2',                '',                 '[C] Analog L',          '[C] ZL',              '[N] Z',             'ZL',                'L',                 'L',                 '',                  'Z',                 'SL',                'LT',                'Analog LT',         'L2',                'L',                 'LT',                'L',                 'L',                 ],
    ['L1',                'L1',                '',                 '[C] ZL',                '[C] L',               '[N] C',             'L',                 '',                  'ZL',                'X',                 'L',                 'L | R',             'LB',                'LB',                'L',                 'X',                 'LB',                '',                  'White',             ],
    ['',                  '',                  '',                 '[C] Digital L',         '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  'Digital LT',        '',                  '',                  '',                  '',                  '',                  ],
    ['L3',                'L3',                '',                 '[W] 1',                 '[W] 1',               '',                  'L Stick',           '',                  '',                  '',                  '',                  'Stick click',       'L Stick',           'L grip',            'L Stick',           '',                  'L Stick',           '',                  '',                  ],
    ['R2',                'R2',                '',                 '[C] Analog R',          '[C] ZR',              '[W] B',             'ZR',                'R',                 'R',                 '',                  'ZR',                'SR',                'RT',                'Analog RT',         'R2',                'R',                 'RT',                'R',                 'R',                 ],
    ['R1',                'R1',                '',                 '[C] ZR',                '[C] R',               '',                  'R',                 '',                  'ZR',                'Z',                 'R',                 'ZL | ZR',           'RB',                'RB',                'R',                 'Z',                 'RB',                'Z',                 'Black',             ],
    ['',                  '',                  '',                 '[C] Digital R',         '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  'Digital RT',        '',                  '',                  '',                  '',                  '',                  ],
    ['R3',                'R3',                '',                 '[W] 2',                 '[W] 2',               '',                  'R Stick',           '',                  '',                  '',                  '',                  '',                  'R Stick',           'R grip',            'R Stick',           '',                  'R Stick',           '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['BRX MENU',          'BRX MENU',          'BRX MENU',         'BRX MENU',              'BRX MENU',            'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          'BRX MENU',          ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
    ['',                  '',                  '',                 '',                      '',                    '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  '',                  ],
];

export const brUuid = [
    "56830f56-5180-fab0-314b-2fa176799a00",
    "56830f56-5180-fab0-314b-2fa176799a01",
    "56830f56-5180-fab0-314b-2fa176799a02",
    "56830f56-5180-fab0-314b-2fa176799a03",
    "56830f56-5180-fab0-314b-2fa176799a04",
    "56830f56-5180-fab0-314b-2fa176799a05",
    "56830f56-5180-fab0-314b-2fa176799a06",
    "56830f56-5180-fab0-314b-2fa176799a07",
    "56830f56-5180-fab0-314b-2fa176799a08",
    "56830f56-5180-fab0-314b-2fa176799a09",
    "56830f56-5180-fab0-314b-2fa176799a0a",
    "56830f56-5180-fab0-314b-2fa176799a0b",
    '56830f56-5180-fab0-314b-2fa176799a0c',
];

export const block = 4096;
export const pakSize = 32 * 1024;
export const vmuSize = 128 * 1024;
export const mtu = 244;

export const urlLatestRelease = 'https://api.github.com/repos/darthcloud/BlueRetro/releases/latest'

export const cfg_cmd_get_abi_ver = 0x01;
export const cfg_cmd_get_fw_ver = 0x02;
export const cfg_cmd_get_bdaddr = 0x03;
export const cfg_cmd_get_gameid = 0x04;
export const cfg_cmd_get_cfg_src = 0x05;
export const cfg_cmd_get_file = 0x06;
export const cfg_cmd_get_fw_name = 0x07;
export const cfg_cmd_set_default_cfg = 0x10;
export const cfg_cmd_set_gameid_cfg = 0x11;
export const cfg_cmd_open_dir = 0x12;
export const cfg_cmd_close_dir = 0x13;
export const cfg_cmd_del_file = 0x14;
export const cfg_cmd_sys_deep_sleep = 0x37;
export const cfg_cmd_sys_reset = 0x38;
export const cfg_cmd_sys_factory = 0x39;
export const cfg_cmd_ota_end = 0x5A;
export const cfg_cmd_ota_start = 0xA5;
export const cfg_cmd_ota_abort = 0xDE;

export const btn = {
    PAD_LX_LEFT: 0,
    PAD_LX_RIGHT: 1,
    PAD_LY_DOWN: 2,
    PAD_LY_UP: 3,
    PAD_RX_LEFT: 4,
    PAD_RX_RIGHT: 5,
    PAD_RY_DOWN: 6,
    PAD_RY_UP: 7,
    PAD_LD_LEFT: 8,
    PAD_LD_RIGHT: 9,
    PAD_LD_DOWN: 10,
    PAD_LD_UP: 11,
    PAD_RD_LEFT: 12,
    PAD_RD_RIGHT: 13,
    PAD_RD_DOWN: 14,
    PAD_RD_UP: 15,
    PAD_RB_LEFT: 16,
    PAD_RB_RIGHT: 17,
    PAD_RB_DOWN: 18,
    PAD_RB_UP: 19,
    PAD_MM: 20,
    PAD_MS: 21,
    PAD_MT: 22,
    PAD_MQ: 23,
    PAD_LM: 24,
    PAD_LS: 25,
    PAD_LT: 26,
    PAD_LJ: 27,
    PAD_RM: 28,
    PAD_RS: 29,
    PAD_RT: 30,
    PAD_RJ: 31,
    MOUSE_X_LEFT: 4,
    MOUSE_X_RIGHT: 5,
    MOUSE_Y_DOWN: 6,
    MOUSE_Y_UP: 7,
    MOUSE_WX_LEFT: 12,
    MOUSE_WX_RIGHT: 13,
    MOUSE_WY_DOWN: 14,
    MOUSE_WY_UP: 15,
    MOUSE_LEFT: 28,
    MOUSE_MIDDLE: 27,
    MOUSE_RIGHT: 24,
    MOUSE_4: 16,
    MOUSE_5: 17,
    MOUSE_6: 18,
    MOUSE_7: 19,
    MOUSE_8: 29,
    KB_A: 0,
    KB_D: 1,
    KB_S: 2,
    KB_W: 3,
    KB_LEFT: 8,
    KB_RIGHT: 9,
    KB_DOWN: 10,
    KB_UP: 11,
    KB_Q: 16,
    KB_R: 17,
    KB_E: 18,
    KB_F: 19,
    KB_ESC: 20,
    KB_ENTER: 21,
    KB_LWIN: 22,
    KB_HASH: 23,
    KB_Z: 25,
    KB_LCTRL: 26,
    KB_X: 29,
    KB_LSHIFT: 30,
    KB_SPACE: 31,
    KB_B: 32,
    KB_C: 33,
    KB_G: 34,
    KB_H: 35,
    KB_I: 36,
    KB_J: 37,
    KB_K: 38,
    KB_L: 39,
    KB_M: 40,
    KB_N: 41,
    KB_O: 42,
    KB_P: 43,
    KB_T: 44,
    KB_U: 45,
    KB_V: 46,
    KB_Y: 47,
    KB_1: 48,
    KB_2: 49,
    KB_3: 50,
    KB_4: 51,
    KB_5: 52,
    KB_6: 53,
    KB_7: 54,
    KB_8: 55,
    KB_9: 56,
    KB_0: 57,
    KB_BACKSPACE: 58,
    KB_TAB: 59,
    KB_MINUS: 60,
    KB_EQUAL: 61,
    KB_LEFTBRACE: 62,
    KB_RIGHTBRACE: 63,
    KB_BACKSLASH: 64,
    KB_SEMICOLON: 65,
    KB_APOSTROPHE: 66,
    KB_GRAVE: 67,
    KB_COMMA: 68,
    KB_DOT: 69,
    KB_SLASH: 70,
    KB_CAPSLOCK: 71,
    KB_F1: 72,
    KB_F2: 73,
    KB_F3: 74,
    KB_F4: 75,
    KB_F5: 76,
    KB_F6: 77,
    KB_F7: 78,
    KB_F8: 79,
    KB_F9: 80,
    KB_F10: 81,
    KB_F11: 82,
    KB_F12: 83,
    KB_PSCREEN: 84,
    KB_SCROLL: 85,
    KB_PAUSE: 86,
    KB_INSERT: 87,
    KB_HOME: 88,
    KB_PAGEUP: 89,
    KB_DEL: 90,
    KB_END: 91,
    KB_PAGE_DOWN: 92,
    KB_NUMLOCK: 93,
    KB_KP_DIV: 94,
    KB_KP_MULTI: 95,
    KB_KP_MINUS: 96,
    KB_KP_PLUS: 97,
    KB_KP_ENTER: 98,
    KB_KP_1: 99,
    KB_KP_2: 100,
    KB_KP_3: 101,
    KB_KP_4: 102,
    KB_KP_5: 103,
    KB_KP_6: 104,
    KB_KP_7: 105,
    KB_KP_8: 106,
    KB_KP_9: 107,
    KB_KP_0: 108,
    KB_KP_DOT: 109,
    KB_LALT: 110,
    KB_RCTRL: 111,
    KB_RSHIFT: 112,
    KB_RALT: 113,
    KB_RWIN: 114,
    CB_BASE_1: 118,
    CB_BASE_2: 119,
    CB_BASE_3: 120,
    CB_BASE_4: 121,
    CB_SYS_RESET: 122,
    CB_BT_PAIR: 123,
    CB_SYS_PWOFF: 124,
    CB_FACT_RST: 125,
    CB_DEEP_SLP: 126,
    CB_WIRED_RST: 127,
};

export const labelName = [
    "PS3",
    "PS4 / PS5",
    "Wiimote",
    "Wiimote + Classic",
    "Wiimote + Classic Pro",
    "Wiimote + Nunchuck",
    "WiiU / Switch Pro",
    "Switch NES",
    "Switch SNES",
    "Switch MD / Genesis",
    "Switch N64",
    "Switch Joycon",
    "Xbox One S / X|S",
    "Steam",
    "8bitdo SN30/SF30",
    "8bitdo M30",
    "Google Stadia",
    "Exlene GameCube",
    "OG XBOX",
];

export const systemCfg = [
    'Auto',
    'Parallel_1P_PP',
    'Parallel_2P_PP',
    'NES',
    'PCE',
    'MD-Genesis',
    'SNES',
    'CD-i',
    'CD32',
    '3DO',
    'Jaguar',
    'PSX',
    'Saturn',
    'PC-FX',
    'JVS',
    'N64',
    'DC',
    'PS2',
    'GC',
    'Wii-Ext',
    "VB",
    "Parallel_1P_OD",
    "Parallel_2P_OD",
    "SEA Board",
];

export const multitapCfg = [
    'None',
    'Slot 1',
    'Slot 2',
    'Dual',
    'Alt',
];

export const inquiryMode = [
    'Auto',
    'Manual',
];

export const devCfg = [
    'GamePad',
    'GamePadAlt',
    'Keyboard',
    'Mouse',
];

export const accCfg = [
    'None',
    'Memory',
    'Rumble',
    'Both',
];

export const turboMask = {
    'Disable': 0,
    '1/2 frames': (1 << 1) | 0,
    '1/4 frames': (3 << 1) | 0,
    '2/4 frames': (2 << 1) | 0,
    '3/4 frames': (3 << 1) | 1,
    '1/8 frames': (7 << 1) | 0,
    '2/8 frames': (6 << 1) | 0,
    '4/8 frames': (4 << 1) | 0,
    '6/8 frames': (6 << 1) | 1,
    '7/8 frames': (7 << 1) | 1,
    '1/16 frames': (15 << 1) | 0,
    '2/16 frames': (14 << 1) | 0,
    '4/16 frames': (12 << 1) | 0,
    '8/16 frames': (8 << 1) | 0,
    '12/16 frames': (12 << 1) | 1,
    '14/16 frames': (14 << 1) | 1,
    '15/16 frames': (15 << 1) | 1,
    '1/32 frames': (31 << 1) | 0,
    '2/32 frames': (30 << 1) | 0,
    '4/32 frames': (28 << 1) | 0,
    '8/32 frames': (24 << 1) | 0,
    '16/32 frames': (16 << 1) | 0,
    '24/32 frames': (24 << 1) | 1,
    '28/32 frames': (28 << 1) | 1,
    '30/32 frames': (30 << 1) | 1,
    '31/32 frames': (31 << 1) | 1,
    '1/64 frames': (63 << 1) | 0,
    '2/64 frames': (62 << 1) | 0,
    '4/64 frames': (60 << 1) | 0,
    '8/64 frames': (56 << 1) | 0,
    '16/64 frames': (48 << 1) | 0,
    '32/64 frames': (32 << 1) | 0,
    '48/64 frames': (48 << 1) | 1,
    '56/64 frames': (56 << 1) | 1,
    '60/64 frames': (60 << 1) | 1,
    '62/64 frames': (62 << 1) | 1,
    '63/64 frames': (63 << 1) | 1,
    '1/128 frames': (127 << 1) | 0,
    '2/128 frames': (126 << 1) | 0,
    '4/128 frames': (124 << 1) | 0,
    '8/128 frames': (120 << 1) | 0,
    '16/128 frames': (112 << 1) | 0,
    '32/128 frames': (96 << 1) | 0,
    '64/128 frames': (64 << 1) | 0,
    '96/128 frames': (96 << 1) | 1,
    '112/128 frames': (112 << 1) | 1,
    '120/128 frames': (120 << 1) | 1,
    '124/128 frames': (124 << 1) | 1,
    '126/128 frames': (126 << 1) | 1,
    '127/128 frames': (127 << 1) | 1,
};

export const scaling = [
    'Linear',
    'Aggressive',
    'Relaxed',
    'Wide',
    'S-Curve',
    'Passthrough',
];

export const diagScaling = [
    'Passthrough',
    'Circular->Square',
    'Circular->N64 Hexagone',
    'Square->Circular',
    'Square->N64 Hexagone'
];

export const maxMainInput = 12;
export const maxOutput = 12;
export const maxMax = 255;
export const maxThres = 100;
